lista = ["Madrid", "San Juan", "Irlanda", "Chicago", "Andorra"]
print (*lista)
sorted(lista)
print (*lista)
print (*sorted(lista))
print (*lista)
lista.reverse()
print (*lista)
lista.reverse()
print (*lista)
lista.sort()
print (*lista)
lista.sort(reverse = True)
print (*lista)